# Project: Sales Data using Pandas and Numpy 

In [29]:
df=pd.read_csv(r"E:\Data-Analysis-Project\sales-data.csv")
df.head()

Unnamed: 0  Order ID                     Product  Quantity Ordered  \
0           0    176558        USB-C Charging Cable                 2   
1           2    176559  Bose SoundSport Headphones                 1   
2           3    176560                Google Phone                 1   
3           4    176560            Wired Headphones                 1   
4           5    176561            Wired Headphones                 1   

   Price Each      Order Date                      Purchase Address  Month  \
0       11.95  04/19/19 08:46          917 1st St, Dallas, TX 75001      4   
1       99.99  04/07/19 22:30     682 Chestnut St, Boston, MA 02215      4   
2      600.00  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
3       11.99  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
4       11.99  04/30/19 09:27     333 8th St, Los Angeles, CA 90001      4   

                City  
0       Dallas  (TX)  
1       Boston  (MA)  
2  Los Angeles  (CA)  
3  Los Angeles  (CA)  
4  Los Angeles  (CA)

In [31]:
df['sales']=df['Quantity Ordered']*df['Price Each']
df.head()

Unnamed: 0  Order ID                     Product  Quantity Ordered  \
0           0    176558        USB-C Charging Cable                 2   
1           2    176559  Bose SoundSport Headphones                 1   
2           3    176560                Google Phone                 1   
3           4    176560            Wired Headphones                 1   
4           5    176561            Wired Headphones                 1   

   Price Each      Order Date                      Purchase Address  Month  \
0       11.95  04/19/19 08:46          917 1st St, Dallas, TX 75001      4   
1       99.99  04/07/19 22:30     682 Chestnut St, Boston, MA 02215      4   
2      600.00  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
3       11.99  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
4       11.99  04/30/19 09:27     333 8th St, Los Angeles, CA 90001      4   

                City   sales  
0       Dallas  (TX)   23.90  
1       Boston  (MA)   99.99  
2  Los Angeles  (CA)  600.00  
3  Los Angeles  (CA)   11.99  
4  Los Angeles  (CA)   11.99

In [42]:
g=df.groupby('Month')
for a,b in g:
    print(a)
    print(b['sales'].sum())


1
1822256.73
2
2202022.42
3
2807100.38
4
3390670.2399999993
5
3152606.7499999995
6
2577802.26
7
2647775.76
8
2244467.88
9
2097560.13
10
3736726.8799999994
11
3199603.1999999997
12
4613443.34


In [41]:
df.groupby('City')['Quantity Ordered'].sum()

City
Atlanta  (GA)          16602
Austin  (TX)           11153
Boston  (MA)           22528
Dallas  (TX)           16730
Los Angeles  (CA)      33289
New York City  (NY)    27932
Portland  (ME)          2750
Portland  (OR)         11303
San Francisco  (CA)    50239
Seattle  (WA)          16553
Name: Quantity Ordered, dtype: int64

In [43]:
df['hour']=pd.to_datetime(df['Order Date']).dt.hour
df.head()

Unnamed: 0  Order ID                     Product  Quantity Ordered  \
0           0    176558        USB-C Charging Cable                 2   
1           2    176559  Bose SoundSport Headphones                 1   
2           3    176560                Google Phone                 1   
3           4    176560            Wired Headphones                 1   
4           5    176561            Wired Headphones                 1   

   Price Each      Order Date                      Purchase Address  Month  \
0       11.95  04/19/19 08:46          917 1st St, Dallas, TX 75001      4   
1       99.99  04/07/19 22:30     682 Chestnut St, Boston, MA 02215      4   
2      600.00  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
3       11.99  04/12/19 14:38  669 Spruce St, Los Angeles, CA 90001      4   
4       11.99  04/30/19 09:27     333 8th St, Los Angeles, CA 90001      4   

                City   sales  hour  
0       Dallas  (TX)   23.90     8  
1       Boston  (MA)   99.99    22  
2  Los Angeles  (CA)  600.00    14  
3  Los Angeles  (CA)   11.99    14  
4  Los Angeles  (CA)   11.99     9

In [44]:
df.groupby('hour')['sales'].sum()

hour
0      713721.27
1      460866.88
2      234851.44
3      145757.89
4      162661.01
5      230679.82
6      448113.00
7      744854.12
8     1192348.97
9     1639030.58
10    1944286.77
11    2300610.24
12    2316821.34
13    2155389.80
14    2083672.73
15    1941549.60
16    1904601.31
17    2129361.61
18    2219348.30
19    2412938.54
20    2281716.24
21    2042000.86
22    1607549.21
23    1179304.44
Name: sales, dtype: float64

In [62]:
df=df[df['Order ID'].duplicated(keep=False)]

In [63]:
data=[]
for i in df['Order ID'].unique():
    #print(i)
    s=tuple(df['Product'][df['Order ID']==i])
    print(s)
    data.append(s)
data    

('Google Phone', 'Wired Headphones')
('Google Phone', 'USB-C Charging Cable')
('Bose SoundSport Headphones', 'Bose SoundSport Headphones')
('AAA Batteries (4-pack)', 'Google Phone')
('Lightning Charging Cable', 'USB-C Charging Cable')
('Apple Airpods Headphones', 'ThinkPad Laptop')
('Bose SoundSport Headphones', 'AAA Batteries (4-pack)')
('34in Ultrawide Monitor', 'Google Phone')
('Lightning Charging Cable', 'USB-C Charging Cable')
('iPhone', 'Lightning Charging Cable')
('Google Phone', 'Bose SoundSport Headphones', 'Wired Headphones')
('Google Phone', 'USB-C Charging Cable')
('Google Phone', 'Wired Headphones')
('Google Phone', 'Wired Headphones')
('AAA Batteries (4-pack)', '27in FHD Monitor')
('USB-C Charging Cable', 'AAA Batteries (4-pack)')
('Google Phone', 'USB-C Charging Cable')
('iPhone', 'Wired Headphones')
('iPhone', 'Wired Headphones')
('iPhone', '27in 4K Gaming Monitor')
('iPhone', 'Lightning Charging Cable')
('ThinkPad Laptop', 'AAA Batteries (4-pack)')
('iPhone', 'Apple Ai

[('Google Phone', 'Wired Headphones'),
 ('Google Phone', 'USB-C Charging Cable'),
 ('Bose SoundSport Headphones', 'Bose SoundSport Headphones'),
 ('AAA Batteries (4-pack)', 'Google Phone'),
 ('Lightning Charging Cable', 'USB-C Charging Cable'),
 ('Apple Airpods Headphones', 'ThinkPad Laptop'),
 ('Bose SoundSport Headphones', 'AAA Batteries (4-pack)'),
 ('34in Ultrawide Monitor', 'Google Phone'),
 ('Lightning Charging Cable', 'USB-C Charging Cable'),
 ('iPhone', 'Lightning Charging Cable'),
 ('Google Phone', 'Bose SoundSport Headphones', 'Wired Headphones'),
 ('Google Phone', 'USB-C Charging Cable'),
 ('Google Phone', 'Wired Headphones'),
 ('Google Phone', 'Wired Headphones'),
 ('AAA Batteries (4-pack)', '27in FHD Monitor'),
 ('USB-C Charging Cable', 'AAA Batteries (4-pack)'),
 ('Google Phone', 'USB-C Charging Cable'),
 ('iPhone', 'Wired Headphones'),
 ('iPhone', 'Wired Headphones'),
 ('iPhone', '27in 4K Gaming Monitor'),
 ('iPhone', 'Lightning Charging Cable'),
 ('ThinkPad Laptop', 'AA

In [66]:
data=pd.Series(data)
data.value_counts().head(10)

(iPhone, Lightning Charging Cable)                        882
(Google Phone, USB-C Charging Cable)                      856
(iPhone, Wired Headphones)                                361
(Vareebadd Phone, USB-C Charging Cable)                   312
(Google Phone, Wired Headphones)                          303
(iPhone, Apple Airpods Headphones)                        286
(Google Phone, Bose SoundSport Headphones)                161
(Vareebadd Phone, Wired Headphones)                       104
(Google Phone, USB-C Charging Cable, Wired Headphones)     77
(Vareebadd Phone, Bose SoundSport Headphones)              60
dtype: int64

# Project: CCPP Dataset using Pandas and Numpy 

In [2]:

import numpy as np
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])


b = np.array([0, 2, 0, 1])



In [10]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
b

array([0, 2, 0, 1])

In [12]:
a[0,0]

1

In [13]:
a[[0,0],[0,1]]

array([1, 2])

In [14]:
a[[0,1,2,3],b]

array([ 1,  6,  7, 11])

In [27]:
import pandas as pd
df=pd.read_csv(r"E:\DataScience-data\combined_cycle_power_plant.csv",sep=';')